require: rubocop-rails
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
AllCops:
  Exclude:
    - 'config.ru'
    - 'Rakefile'
    - 'app/channels/**/*'
    - 'app/controllers/**/*'
    - 'app/jobs/**/*'
    - 'app/mailers/**/*'
    - 'app/views/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'