require: rubocop-rails
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'